export const projsData = [
    {
        id: "proj-1",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703109021/new_portfolio/blog_rwxm7q.webp",
        title: "BlogBox",
        desc: "Offering an intuitive and collaborative space for crafting and sharing insightful technical blogs; with AI-powered autocompletions.",
        github: "https://github.com/gateremark/blogbox",
        live: "https://myblogbox.vercel.app/",
        tech: [
            "NextJS,",
            "TailwindCSS,",
            "OpenAI API,",
            "NeonDB,",
            "Drizzle ORM,",
            "Next Auth",
        ],
    },
    {
        id: "proj-2",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703109021/new_portfolio/home_vm6hdd.webp",
        title: "HomeTopia",
        desc: "Designed to connect prospective homeowners, tenants, and real estate professionals with their perfect housing solutions.",
        github: "https://github.com/gateremark/hometopia",
        live: "https://hometopia.vercel.app/",
        tech: ["React,", "TailwindCSS,", "Firebase,", "SwiperJS,", "Leaflet"],
    },
    {
        id: "proj-3",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703109022/new_portfolio/bot_pyp3fk.webp",
        title: "gaterebot",
        desc: "Leveraging advanced natural language processing techniques to provide users with an interactive conversational experience.",
        github: "https://github.com/gateremark/gaterebot",
        live: "https://gaterebot.vercel.app/",
        tech: [
            "NextJS,",
            "TailwindCSS,",
            "OpenAI API,",
            "MongoDB,",
            "Next Auth",
        ],
    },
    {
        id: "proj-4",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703109021/new_portfolio/maps2_ezsfin.webp",
        title: "Gatere Maps",
        desc: "A Google Maps‐inspired project, allowing users to explore interactive maps, and search for locations using a built‐in search feature.",
        github: "https://github.com/gateremark/google_maps_clone",
        live: "https://gateremaps.vercel.app/",
        tech: ["React,", "TailwindCSS,", "Maps API,", "GeoCoding API"],
    },
    {
        id: "proj-5",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703109021/new_portfolio/movie_dwo2xb.webp",
        title: "FilMere",
        desc: "A movie app utilizing the TMDB API to fetch movie data and provides a user-friendly interface for users to browse and explore various movies.",
        github: "https://github.com/gateremark/FilMere",
        live: "https://gateremark.github.io/FilMere/",
        tech: ["HTML,", "CSS,", "JavaScript,", "TMDB API"],
    },
];
