export const projsData = [
    {
        id: "proj-1",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703109021/new_portfolio/blog_rwxm7q.webp",
        title: "BlogBox",
        desc: "Offering an intuitive and collaborative space for crafting and sharing insightful technical blogs; with AI-powered autocompletions.",
        github: "https://github.com/gateremark/blogbox",
        live: "https://myblogbox.vercel.app/",
        tech: [
            "NextJS,",
            "TailwindCSS,",
            "OpenAI API,",
            "NeonDB,",
            "Drizzle ORM,",
            "Next Auth",
        ],
    },
    {
        id: "proj-2",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703109021/new_portfolio/home_vm6hdd.webp",
        title: "HomeTopia",
        desc: "Designed to connect prospective homeowners, tenants, and real estate professionals with their perfect housing solutions.",
        github: "https://github.com/gateremark/hometopia",
        live: "https://hometopia.vercel.app/",
        tech: ["React,", "TailwindCSS,", "Firebase,", "SwiperJS,", "Leaflet"],
    },
    {
        id: "proj-3",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703109022/new_portfolio/bot_pyp3fk.webp",
        title: "gaterebot",
        desc: "Leveraging advanced natural language processing techniques to provide users with an interactive conversational experience.",
        github: "https://github.com/gateremark/gaterebot",
        live: "https://gaterebot.vercel.app/",
        tech: [
            "NextJS,",
            "TailwindCSS,",
            "OpenAI API,",
            "MongoDB,",
            "Next Auth",
        ],
    },
    {
        id: "proj-4",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703109021/new_portfolio/maps2_ezsfin.webp",
        title: "Gatere Maps",
        desc: "A Google Maps‐inspired project, allowing users to explore interactive maps, and search for locations using a built‐in search feature.",
        github: "https://github.com/gateremark/google_maps_clone",
        live: "https://gateremaps.vercel.app/",
        tech: ["React,", "TailwindCSS,", "Maps API,", "GeoCoding API"],
    },
    {
        id: "proj-5",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703109021/new_portfolio/movie_dwo2xb.webp",
        title: "FilMere",
        desc: "A movie app utilizing the TMDB API to fetch movie data and provides a user-friendly interface for users to browse and explore various movies.",
        github: "https://github.com/gateremark/FilMere",
        live: "https://gateremark.github.io/FilMere/",
        tech: ["HTML,", "CSS,", "JavaScript,", "TMDB API"],
    },
    {
        id: "proj-6",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703148140/new_portfolio/nindmatch_mkdeem.webp",
        title: "MindMatch",
        desc: "A React practice project. A simple memory game where the user has to match the cards with the same images.",
        github: "https://github.com/gateremark/mind-match",
        live: "https://mind-match.vercel.app/",
        tech: ["ReactJS"],
    },
    {
        id: "proj-7",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703148140/new_portfolio/droppi_rtspsa.webp",
        title: "Droppi",
        desc: "A simple Kanban board project that allows one to create tasks and organize them into different stages.",
        github: "https://github.com/gateremark/droppi-kanban-board",
        live: "https://droppi.vercel.app/",
        tech: ["HTML,", "CSS,", "JavaScript"],
    },
    {
        id: "proj-8",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703148140/new_portfolio/secretno_ihqsiu.webp",
        title: "Secret Numbers",
        desc: "DOM Manipulation practice project. A simple game where the user has to guess a secret number between 1 and 20.",
        github: "https://github.com/gateremark/secret_number_guess_game",
        live: "https://gateremark.github.io/secret_number_guess_game/",
        tech: ["HTML,", "CSS,", "JavaScript"],
    },
    {
        id: "proj-9",
        imgUrl: "https://res.cloudinary.com/dvuazircp/image/upload/v1703148140/new_portfolio/makifoods_evlwgs.webp",
        title: "MakiFoods",
        desc: "HTML and CSS practice project. A simple meals website with a responsive design and a mobile-first approach.",
        github: "https://github.com/gateremark/Makifoods",
        live: "https://gateremark.github.io/Makifoods/",
        tech: ["HTML,", "CSS"],
    },
];
