export const workData = [
	{
		title: "Frontend Developer",
		company_name: "Google",
		icon: "https://res.cloudinary.com/dvuazircp/image/upload/v1697319684/google_bsro6q.webp",
		iconBg: "#383E56",
		date: "March 2020 - Present",
		points: [
			"Developing and maintaining web applications using React.js and other related technologies.",
			"Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
			"Implementing responsive design and ensuring cross-browser compatibility.",
			"Participating in code reviews and providing constructive feedback to other developers.",
		],
	},
	{
		title: "React Native Developer",
		company_name: "Tesla",
		icon: "https://res.cloudinary.com/dvuazircp/image/upload/v1697220933/tesla_shlymo.webp",
		iconBg: "#E6DEDD",
		date: "Jan 2021 - Feb 2022",
		points: [
			"Developing and maintaining web applications using React.js and other related technologies.",
			"Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
			"Implementing responsive design and ensuring cross-browser compatibility.",
			"Participating in code reviews and providing constructive feedback to other developers.",
		],
	},
	{
		title: "Web Developer",
		company_name: "Netflix",
		icon: "https://res.cloudinary.com/dvuazircp/image/upload/v1697320452/netflix_g8v48j.webp",
		iconBg: "#383E56",
		date: "Jan 2022 - Jan 2023",
		points: [
			"Developing and maintaining web applications using React.js and other related technologies.",
			"Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
			"Implementing responsive design and ensuring cross-browser compatibility.",
			"Participating in code reviews and providing constructive feedback to other developers.",
		],
	},
	{
		title: "Full-Stack Developer",
		company_name: "Meta",
		icon: "https://res.cloudinary.com/dvuazircp/image/upload/v1697220933/meta_v3qda5.webp",
		iconBg: "#E6DEDD",
		date: "Jan 2023 - Feb 2024",
		points: [
			"Developing and maintaining web applications using React.js and other related technologies.",
			"Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
			"Implementing responsive design and ensuring cross-browser compatibility.",
			"Participating in code reviews and providing constructive feedback to other developers.",
		],
	},
	{
		title: "ReactJS Developer",
		company_name: "Microsoft",
		icon: "https://res.cloudinary.com/dvuazircp/image/upload/v1697220933/ms_yixnxm.webp",
		iconBg: "#383E56",
		date: "March 2020 - April 2025",
		points: [
			"Developing and maintaining web apps using React.js and other related technologies.",
			"Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
			"Implementing responsive design and ensuring cross-browser compatibility.",
			"Participating in code reviews and providing constructive feedback to other developers.",
		],
	},
];
